# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e66565ddf98d2f8181439dd7d95f52d25a43ac2df04c3301316f95b39e8700c3befe2e45c86130893a2654bba5a4f85073c80422b2b2bdd79e979f3368f7cc3f

test:
  secret_key_base: 3a4f210b372aa87dee0672b1f5c55137dc3c6ea23a784e5309ba35495946d9de080ca05c5654198b7314795bacf37f82f49e7d258e76f9d021b267098fa58f03

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
